%YAML:1.0

# camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: -0.0407003
   k2: 0.00997319
   p1: -0.000548556
   p2: -0.000113034
projection_parameters:
   fx: 528.925
   fy: 528.595
   cx: 632.465
   cy: 358.6545

# Feature Tracker Parameters
stride: 2               # only process every `stride`th frame
equalize: 1             # histogram equalization for lighting variance
border_margin: 1        # ignore the features found in border pixels
min_distance: 30        # GFTT minimum distance
max_features: 150       # number of GFTT to maintain
F_reproj_error: 1.0     # reprojection error threshold for findFundamentalMat